[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"

[[redirects]]
    force = true
    from = "/*"
    status = 200
    to = "/.netlify/functions/:splat"

[build]
    command = "echo 'Build functions'"
    functions = "netlify/functions"
